author:
  name: "İpek"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Merhaba, Ben 3. sınıf yazılım mühendisliği öğrencisiyim."
  location: "İstanbul/Türkiye"
  email: sevvalipektopcu@gmail.com
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sevvalipektopcu@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ipekk191"

kramdown:
  input: GFM
  math_engine: null
  auto_ids: true

incremental: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
#  - jekyll-include-cache  <-- kaldırdın zaten

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true   # avatar ve profil görünmesi için gerekli
      read_time: true
      comments: true
      share: true
      related: true
