author: ipek
  
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"


kramdown:
  input: GFM
  math_engine: null
  auto_ids: true

incremental: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache  <-- kaldırdın zaten

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true   # avatar ve profil görünmesi için gerekli
      read_time: true
      comments: true
      share: true
      related: true
