author:
  name: "İpek"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Merhaba, Ben 3. sınıf yazılım mühendisliği öğrencisiyim."
  location: "İstanbul/Türkiye"

kramdown:
  input: GFM
  math_engine: null  # mathjax kapalı
  auto_ids: true

incremental: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
